version: '3.9'

services:
  ui:
    image: ui:0.0.1
    container_name: ui-c
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
    volumes:
      - type: bind
        source: ./frontend/src
        target: /app/src
    depends_on:
      - server
  server:
    image: server:0.0.1
    container_name: server-c
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./backend/src
        target: /app/src
      - type: bind
        source: ./backend/node_modules
        target: /app/node_modules
    depends_on:
      - db
  db:
    image: db:0.0.1
    container_name: db-c
    build: 
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 27017:27017
    volumes:
      - ./db/data:/data

